### ISSUE TITLE
Problem with duplicated VMInfo

### ISSUE THREAD

**Issue by capaaway** [ercole-io/ercole-agent-virtualization#31]
Oct  1 15:51:29 XXXXXX java: Caused by: org.springframework.dao.IncorrectResultSizeDataAccessException: query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2

It seems that if we have a duplicated vms on database, ercole-agent-virtualization can't send the new data:

ercole=> select * from vminfo WHERE host_name='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
  id   |    cluster_name    |          host_name          |   name
-------+--------------------+-----------------------------+-----------
 40040 | XXXXXX-XXXXX      | pippo | PIPPOVM
 38702 | YYYYYYYYYYYYY | pippo | PIPPOVM
(2 rows)

Workaround seems to be to delete row duplicated.

**Comment by amreo** [comment]
I think the bug is that the old cluster isn't deleted.
